### ISSUE TITLE
Questions for the KMeans clustering.

### ISSUE THREAD

**Issue by peterzpy** [CASIA-IVA-Lab/ISP-reID#10]
Thanks for your publication of the code.  As you have said in your paper, the clustering is conducted on the images for the same person, respectively. But how to keep the semantic information for the k clusters unchanged during the clustering on different person's images?  Intuitively, the clustering on different person's images will generate k clusters with different meanings. At least, the semantic information of k clusters can not keep the same order among the clustering. Waiting for your reply, thx. : )

**Comment by zhukuan96** [comment]
We assign the label 0 to background and assign label {1, ..., K} to different body parts according to their average position from top to down (page7 in paper). This will guarantee the semantic consistence in most cases.

**Comment by peterzpy** [comment]
Thanks for your reply, I have understood your idea now.
