### ISSUE TITLE
The performances of ISP-ResNet50.

### ISSUE THREAD

**Issue by deepalchemist** [CASIA-IVA-Lab/ISP-reID#11]
Hi, can you provide the performances of ISP-ResNet50 on Market1501, DukeMTMC, Occluded-Duke, and CUHK03-NP? 
Thank you very much. I plan to compare our method with ISP-ResNet50.

**Comment by zhukuan96** [comment]
Sorry, but I have to say ISP is more suitable to backbones with larger feature maps. The performance of ISP on ResNet50 is not that good as the size of its output feature maps is small.

**Comment by deepalchemist** [comment]
![image](https://user-images.githubusercontent.com/50560933/109373895-8e4da400-78ec-11eb-8396-61f1e8b99775.png)
I observe from Table. 6, on DukeMTMC-reID, the performance of ISP-ResNet50 is comparable to that of ISP-HRNet-W32.
