### ISSUE TITLE
HRNet32 pre-trained parameters

### ISSUE THREAD

**Issue by chanhoeom** [CASIA-IVA-Lab/ISP-reID#12]
Thanks for releasing your code!

![image](https://user-images.githubusercontent.com/25449812/108335610-7f912e00-7216-11eb-892c-287e25c7b072.png)

I have a quick question. Is the provided "pre-trained HRNet32" trained on ImageNet only? i.e. without using any kinds of human pose datasets?

![image](https://user-images.githubusercontent.com/25449812/108335336-2d500d00-7216-11eb-825f-e36053e3080a.png)

Above image is captured from an official github of HRNet. The pre-trained model you use might be "hrnet_w32-XXX" or "hrnet_w48-XXX" right?

**Comment by zhukuan96** [comment]
Yes, only pretrained on ImageNet. You can also use the official link.

**Comment by chanhoeom** [comment]
> Yes, only pretrained on ImageNet. You can also use the official link.

Awesome thanks :)
