### ISSUE TITLE
Predicted ground-truth download

### ISSUE THREAD

**Issue by PierreDim** [CASIA-IVA-Lab/ISP-reID#13]
Hi, I cannot download your SCHP predicted ground-truth as I don't have a Baidu account (only for chinese phone number holders if I'm not wrong?), can you share them with me using another medium? (email, Google Drive, ...)
Thank you :-)

**Comment by zhukuan96** [comment]
Hi, I have sent it to your github email.

**Comment by PierreDim** [comment]
> Hi, I have sent it to your github email.

Hi, I didn't receive your email, can you send it to vladar1380@gmail.com? Thank you
