### ISSUE TITLE
请问聚类会很慢吗？

### ISSUE THREAD

**Issue by aagainbeyond2** [CASIA-IVA-Lab/ISP-reID#15]
如题

**Comment by aagainbeyond2** [comment]
the overall clustering time is about 6.3h/5.4h/3.1h for datasets of DukeMTMCreID/Market1501/CUHK03-NP指的是每个epoch聚类花这么多时间，还是120个epoch一共这么多时间？

**Comment by zhukuan96** [comment]
总共的，利用faiss聚类很快。
