### ISSUE TITLE
请问PGT文件使用SCHP代码生成细节

### ISSUE THREAD

**Issue by liudapeng2333** [CASIA-IVA-Lab/ISP-reID#16]
PGT文件的生成是用的SCHP代码的哪一个模型？作者将SCHP代码做修改了吗？想了解一下

**Comment by zhukuan96** [comment]
用的在LIP上训练的模型。代码没有修改，用的预测的label结果（0-21），然后进行label合并（0-6），不是可视化图像结果（0-255）。

**Comment by liudapeng2333** [comment]
非常感谢您的回复。
您能具体讲一下您把哪些label进行合并了吗？
还有不是可视化结果是您没有使用putpalette调色板函数吗？

**Comment by zhukuan96** [comment]
label合并在论文中和parsing性能验证代码中都有。代码在验证的时候会自动合并，不需要手动处理。你只需要使用SCHP预测的0-21的结果就行，也可以直接用放在百度云上预测好的结果。调色板函数只是为了将label空间映射到可视化空间，在性能验证不需要，可视化才需要。

**Comment by liudapeng2333** [comment]
多谢
