### ISSUE TITLE
请问聚类相关问题

### ISSUE THREAD

**Issue by Cyongchun** [CASIA-IVA-Lab/ISP-reID#17]
您好，您的文章中方法部分3.2节中，生成前景图和各个部位的图，是将相同人物身份的所有图像放在一起聚类还是指单个图像进行操作呢，3.2中的公式2和公式3计算得到的结果是3.1节中的Pk做的解释吗？谢谢！

**Comment by zhukuan96** [comment]
你好，是将相同人物身份的所有图像放在一起聚类；3.2中公式5是3.1中Pk的计算方式。3.1介绍框架，3.2介绍具体实现。

**Comment by Cyongchun** [comment]
非常感谢您的回答，我还有几个问题麻烦您再解答一下，3.2中的公式3和公式4对于公式5有什么作用，我能理解的是一个公式3是为了产生整个人物的特征权重图，公式4是各个部分的权重图，然后将各个计算结果通过全连接层生成Wk，请问是这样吗？

**Comment by zhukuan96** [comment]
公式3、4是聚类产生伪标签过程中需要的归一化操作，不是网络训练过程。公式5是网络对part的预测，训练的时候由6监督。

**Comment by Cyongchun** [comment]
感谢您的解答！
