### ISSUE TITLE
关于backbone

### ISSUE THREAD

**Issue by atk-sheep** [CASIA-IVA-Lab/ISP-reID#18]
请问项目中是只有HRnet作为backbone吗？因为我没有发现别的backbone，但是在文章中是有resnet50、seresnet、hrnet的对比，如果项目中有别的backbone希望作者能够指出，不胜感激！

**Comment by zhukuan96** [comment]
对的，只有HRNet，因为ISP还是更适合用特征分辨率高的网络，其他backbone效果不是很好。
