### ISSUE TITLE
version about the dependent lib?

### ISSUE THREAD

**Issue by carry-xz** [CASIA-IVA-Lab/ISP-reID#2]
Nice work ! It's a very interesting idea , but I can't train with this code . what is the version of ignite？or install it by source?

**Comment by zhukuan96** [comment]
Hi, my pytorch-ignite version is 0.2.0 (and version 0.1.2 may also works). What errors have you encountered?

**Comment by carry-xz** [comment]
thanks for reply，
the error is 
File "/workspace/code/reid/ISP-reID/engine/clustering.py", line 170, in run_kmeans
    losses = faiss.vector_to_array(clus.obj)
AttributeError: 'Clustering' object has no attribute 'obj'

Maybe the faiss is installed incorrectly，but there‘s no import error.

**Comment by zhukuan96** [comment]
Hi, my faiss version is 1.5.2. Please check if you are using python3 and you may find the solution from https://github.com/facebookresearch/faiss/issues/1179.

**Comment by carry-xz** [comment]
thanks , pip install faiss-gpu==1.6.1 , It worked！
