### ISSUE TITLE
Reproduction of the model

### ISSUE THREAD

**Issue by zhaoxin111** [CASIA-IVA-Lab/ISP-reID#20]
Hi,thanks your nice work.
I reproduce the model based on Occluded_DukeMTMC, and the result is much beterr than the result posted on paper, and I did not adjust any relevant hyperparameters
![image](https://user-images.githubusercontent.com/9295202/163491584-54af1eb9-290b-4d3c-b4b5-5b3870491a20.png)

**Comment by zhukuan96** [comment]
That is exciting. After we optimize the source codes and make them open, the performance on Occluded_dukeMTMC is indeed higher than that posted on paper.  But the performance you reproduced is much higher than I expected. Maybe the environment also affects the performance.

**Comment by zhaoxin111** [comment]
This is an amazing result!

**Comment by zhukuan96** [comment]
Thank you. Welcome to pay attention to our new work https://github.com/CASIA-IVA-Lab/PASS-reID.

**Comment by zhaoxin111** [comment]
> Thank you. Welcome to pay attention to our new work https://github.com/CASIA-IVA-Lab/PASS-reID.

AAformer will it be open sourced? I have been following the related papers you published recently.

**Comment by zhaoxin111** [comment]
Recently I am interesting in occluded and partial reID and judging from the recent SOAT, transfer has better local integration and perception capabilities, and reID seems to be another promising direction for transformer.

AAformer and PASS-reID are nice work！

**Comment by zhukuan96** [comment]
Thank you, but AAformer may not be open. The main reasons are (1) its performance is really not that outstanding. (2) PASS with ''part tokens'', one of the main ideas of AAformer, obtains quite good performance. (3) it's been a long time since we proposed it, but it is still not published now. I have an idea to improve it, and maybe we will propose AAformer_v2 later.

You can also try PASS on Occluded-DukeMTMC. According to the privacy policy, we did not conduct experiments on DukeMTMC and its related datasets, but we believe PASS is also effective on occluded datasets.

**Comment by zhaoxin111** [comment]
> Thank you, but AAformer may not be open. The main reasons are (1) its performance is really not that outstanding. (2) PASS with ''part tokens'', one of the main ideas of AAformer, obtains quite good performance. (3) it's been a long time since we proposed it, but it is still not published now. I have an idea to improve it, and maybe we will propose AAformer_v2 later.
> 
> You can also try PASS on Occluded-DukeMTMC. According to the privacy policy, we did not conduct experiments on DukeMTMC and its related datasets, but we believe PASS is also effective on occluded datasets.

Thank you. I will try it.

**Comment by hh23333** [comment]
> Hi,thanks your nice work. I reproduce the model based on Occluded_DukeMTMC, and the result is much beterr than the result posted on paper, and I did not adjust any relevant hyperparameters ![image](https://user-images.githubusercontent.com/9295202/163491584-54af1eb9-290b-4d3c-b4b5-5b3870491a20.png)

Amazing result! @zhaoxin111  I wonder what changes you made to achieve higher results than the paper. Could you please share your modifications and insights? Also, I noticed that you tried to use multiprocessing for clustering. Did you succeed in that? Thank you.😊
