### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/kzhu/DukeMTMC-reID/train_pseudo_labels-ISP-7'

### ISSUE THREAD

**Issue by 2806099072** [CASIA-IVA-Lab/ISP-reID#3]
FileNotFoundError: [Errno 2] No such file or directory: '/data/kzhu/DukeMTMC-reID/train_pseudo_labels-ISP-7'

**Comment by 2806099072** [comment]
Hope to get your answers, thank you

**Comment by zhukuan96** [comment]
Do you change the root dir of DukeMTMC-reID to your path?

**Comment by 2806099072** [comment]
python3 tools/train.py --config_file='configs/softmax_triplet.yml' MODEL.DEVICE_ID "('2')" MODEL.IF_WITH_CENTER "('no')" MODEL.NAME "('HRNet32')" MODEL.PRETRAIN_PATH "('/home/kzhu/.torch/models/hrnetv2_w32_imagenet_pretrained.pth')" DATASETS.NAMES "('dukemtmc')" DATASETS.ROOT_DIR "('/data')" CLUSTERING.PART_NUM "(7)" DATASETS.PSEUDO_LABEL_SUBDIR "('train_pseudo_labels-ISP-7')"  OUTPUT_DIR "('./log/ISP-Duke-7')"

Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main()
  File "tools/train.py", line 110, in main
    train(cfg)
  File "tools/train.py", line 23, in train
    train_loader, val_loader, num_query, num_classes, clustering_loader = make_data_loader(cfg)
  File "./data/build.py", line 20, in make_data_loader
    dataset = init_dataset(cfg.DATASETS.NAMES, pseudo_label_subdir=cfg.DATASETS.PSEUDO_LABEL_SUBDIR, part_num=cfg.CLUSTERING.PART_NUM, root=cfg.DATASETS.ROOT_DIR)
  File "./data/datasets/__init__.py", line 29, in init_dataset
    return __factory[name](*args, **kwargs)
  File "./data/datasets/dukemtmcreid.py", line 47, in __init__
    os.mkdir(self.pseudo_label_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/data/DukeMTMC-reID/train_pseudo_labels-ISP-7'

**Comment by 2806099072** [comment]
DATASETS.PSEUDO_LABEL_SUBDIR "('train_pseudo_labels-ISP-7')"  
do not have this

**Comment by zhukuan96** [comment]
Please check whether 'DukeMTMC-reID' is under '/data'. The 'train_pseudo_labels-ISP-7' will be automatically generated.

**Comment by 2806099072** [comment]
root@405762d7523b:/home/ISP-reID-master# LS
bash: LS: command not found


root@405762d7523b:/home/ISP-reID-master# ls
ISP-CUHK03_detected.sh  ISP-Market1501.sh         README.md     configs  image   modeling  tools
ISP-CUHK03_labeled.sh   ISP-Occluded_DukeMTMC.sh  Visualize.sh  data     layers  solver    utils
ISP-DukeMTMC.sh         LICENSE                   config        engine   log     tests


root@405762d7523b:/home/ISP-reID-master# cd data
root@405762d7523b:/home/ISP-reID-master/data# ls
DukeMTMC-reID  __pycache__  collate_batch.py  samplers
__init__.py    build.py     datasets          transforms


root@405762d7523b:/home/ISP-reID-master/data# cd DukeMTMC-reID


root@405762d7523b:/home/ISP-reID-master/data/DukeMTMC-reID# ls
CITATION.txt               README.md           bounding_box_train_parsing_pgt
DukeMTMC-reID.zip          __MACOSX            bounding_box_train_parsing_pgt.zip
LICENSE_DukeMTMC-reID.txt  bounding_box_test   query
LICENSE_DukeMTMC.txt       bounding_box_train
root@405762d7523b:/home/ISP-reID-master/data/DukeMTMC-reID#

 'DukeMTMC-reID' is under '/data'

according to following:
data
    DukeMTMC-reID
            bounding_box_test/
            bounding_box_train/
            bounding_box_train_parsing_pgt/

**Comment by 2806099072** [comment]
root@405762d7523b:/home/ISP-reID-master# ls
ISP-CUHK03_detected.sh     ISP-Market1501.sh            README.md       configs  image   modeling  tools
ISP-CUHK03_labeled.sh   ISP-Occluded_DukeMTMC.sh  Visualize.sh  data     layers  solver    utils
ISP-DukeMTMC.sh         LICENSE                   config        engine   log     tests

root@405762d7523b:/home/ISP-reID-master# cd data
root@405762d7523b:/home/ISP-reID-master/data# ls
DukeMTMC-reID  __pycache__  collate_batch.py  samplers
__init__.py    build.py     datasets          transforms

root@405762d7523b:/home/ISP-reID-master/data# cd DukeMTMC-reID
root@405762d7523b:/home/ISP-reID-master/data/DukeMTMC-reID# ls

CITATION.txt               README.md           bounding_box_train_parsing_pgt
DukeMTMC-reID.zip          __MACOSX            bounding_box_train_parsing_pgt.zip
LICENSE_DukeMTMC-reID.txt  bounding_box_test   query
LICENSE_DukeMTMC.txt       bounding_box_train
root@405762d7523b:/home/ISP-reID-master/data/DukeMTMC-reID#

 'DukeMTMC-reID' is under '/data'

**Comment by 2806099072** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/data2/kzhu/Market-1501/train_pseudo_labels-ISP-7'

root@405762d7523b:/home/ISP-reID-master# cd data
root@405762d7523b:/home/ISP-reID-master/data# ls
DukeMTMC-reID  __pycache__  collate_batch.py  kzhu      transforms
__init__.py    build.py     datasets          samplers  untitled.txt
root@405762d7523b:/home/ISP-reID-master/data# cd kzhu
root@405762d7523b:/home/ISP-reID-master/data/kzhu# ls
Market-1501  Market-1501-v15.09.15.zip  bounding_box_train_parsing_pgt.zip
root@405762d7523b:/home/ISP-reID-master/data/kzhu# cd Market-1501
root@405762d7523b:/home/ISP-reID-master/data/kzhu/Market-1501# ls
bounding_box_test   bounding_box_train_parsing_pgt  gt_query  readme.txt
bounding_box_train  gt_bbox                         query
root@405762d7523b:/home/ISP-reID-master/data/kzhu/Market-1501#

For the data set ‘Market1501’, the same error occurred, and it shouldn't be the wrong file directory. You said that the file ’train_pseudo_labels-ISP-7’ was automatically generated, but it was never generated, so this file was not found.

**Comment by zhukuan96** [comment]
Please change '/data' to '/home/ISP-reID-master/data' or ''./data'. The absolute path is different from the relative path.

**Comment by 2806099072** [comment]
thank you very much!
