### ISSUE TITLE
About the CPU memory problem.

### ISSUE THREAD

**Issue by abcdvzz** [CASIA-IVA-Lab/ISP-reID#5]
At line 149 of the engine/trainer.py which is the compute_feature function, I found the detach operation causes memory problem of CPU. I notice you have tried Cuda, but after I use Cuda the memory problem(Cuda memory) is still there. I wanna know how I can fix it.

**Comment by abcdvzz** [comment]
![image](https://user-images.githubusercontent.com/27143058/94336289-95f2df00-0014-11eb-98df-aa70edc4a59c.png)
It just got killed by the system and I checked out the memory of CPU (top -p pid). I found the memory consistently improved until it reach 100% then it got killed.

**Comment by zhukuan96** [comment]
It costs about 40~60G CPU memory. If you do not have enough CPU memory, you may first extract features for images of a ID, then conduct the clustering, and do the above for another ID. But this will cost a lot of time.
