### ISSUE TITLE
a question about the provided datasets~

### ISSUE THREAD

**Issue by soulredeem** [CASIA-IVA-Lab/ISP-reID#6]
Why are the predicted ground-truth for person re-ID datasets on PGT all  black pictures？

**Comment by zhukuan96** [comment]
The predicted ground-truth is the label of human parts, but not the visulization of human parts. In label space, the number are from 0 to 19. When directly opening it as a picture, it is all black. You can run the visualize.py to map the prediction from label space to color space (0-255).

**Comment by soulredeem** [comment]
Thanks, lad. I appreciate it.
