### ISSUE TITLE
Why does CPU memory  explode?

### ISSUE THREAD

**Issue by shangangjin** [CASIA-IVA-Lab/ISP-reID#8]
when  i run this code ,the cpu memory will be exploded.my cpu memory is 32G size,

**Comment by zhukuan96** [comment]
The feature maps for person images are saved for clustering.

**Comment by shangangjin** [comment]
How to solve this problem and what size of memory can meet the requirements?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/ISP-reID"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 下午5:53
收件人:&nbsp;"CASIA-IVA-Lab/ISP-reID"<ISP-reID@noreply.github.com&gt;;
抄送:&nbsp;"CSIM_Jin"<1057965981@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/ISP-reID] Why does CPU memory  explode? (#8)





 
The feature maps for person images are saved for clustering.
